name: Update READMEs

on:
  push:
    branches:
      - main
      - master

jobs:
  update-readmes:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Find and replace all readme_ko.md with readme.md
      run: |
        find . -type f -name 'readme_ko.md' | while read file; do
          dir=$(dirname "$file")
          cp "$file" "$dir/readme.md"
        done

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        git commit -m "Update all readme.md files from readme_ko.md"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
